### ISSUE TITLE
AttributeError: module 'sortedcontainers' has no attribute 'SortedKeyList'

### ISSUE THREAD

**Issue by Techno-Fox** [angr/rex#57]
Hello It's me again. So now i ran into another error running test_rex.py

Python version : python 3.7.5
OS : Parrot OS x86

Error : 

Traceback (most recent call last):
  File "test_explore.py", line 48, in <module>
    run_all()
  File "test_explore.py", line 34, in run_all
    all_functions[f]()
  File "test_explore.py", line 21, in test_write_what_where_shadowstack
    crash = rex.Crash(target, inp, rop_cache_path=os.path.join(cache_location, "write_what_where_shadow_stack"))
  File "/usr/local/lib/python3.7/dist-packages/rex-0.2-py3.7.egg/rex/crash.py", line 105, in __init__
  File "/usr/local/lib/python3.7/dist-packages/rex-0.2-py3.7.egg/rex/crash.py", line 511, in _initialize
  File "/usr/local/lib/python3.7/dist-packages/archr/arsenal/angr_project.py", line 44, in fire
    preloader = cle.Loader(the_binary, **preload_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cle/loader.py", line 127, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, preloading=True)
  File "/usr/local/lib/python3.7/dist-packages/cle/loader.py", line 646, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/usr/local/lib/python3.7/dist-packages/cle/loader.py", line 749, in _load_object_isolated
    return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
  File "/usr/local/lib/python3.7/dist-packages/cle/backends/cgc/cgc.py", line 28, in __init__
    super(CGC, self).__init__(stream, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cle/backends/elf/elf.py", line 33, in __init__
    super(ELF, self).__init__(binary, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cle/backends/elf/metaelf.py", line 25, in __init__
    super(MetaELF, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cle/backends/__init__.py", line 96, in __init__
    self.symbols = sortedcontainers.SortedKeyList(key=self._get_symbol_relative_addr)
AttributeError: module 'sortedcontainers' has no attribute 'SortedKeyList'

P.S. Thank you for reading.

**Comment by rhelmot** [comment]
SortedKeyList is only provided by certain versions of sortedcontainers. We have a pin `sortedcontainers>=2.0` to ensure that this is satisfied. Can you please post the output of `pip freeze | grep sortedcontainers` to ensure you have the right version installed?

**Comment by KittyTechnoProgrammer** [comment]
using pip3 I got 

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/freeze.py", line 100, in run
    for line in freeze(**freeze_kwargs):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/freeze.py", line 70, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/freeze.py", line 249, in from_dist
    req, editable, comments = get_requirement_info(dist)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/freeze.py", line 188, in get_requirement_info
    vcs_backend = vcs.get_backend_for_dir(location)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/vcs/versioncontrol.py", line 234, in get_backend_for_dir
    if vcs_backend.controls_location(location):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/vcs/git.py", line 364, in controls_location
    log_failed_cmd=False)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/vcs/versioncontrol.py", line 632, in run_command
    log_failed_cmd=log_failed_cmd)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 190, in call_subprocess
    stdout=subprocess.PIPE, cwd=cwd, env=env,
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.7/dist-packages/tracer-0.1-py3.7.egg'

And pip I got 

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/freeze.py", line 100, in run
    for line in freeze(**freeze_kwargs):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/freeze.py", line 70, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/freeze.py", line 249, in from_dist
    req, editable, comments = get_requirement_info(dist)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/freeze.py", line 188, in get_requirement_info
    vcs_backend = vcs.get_backend_for_dir(location)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/vcs/versioncontrol.py", line 234, in get_backend_for_dir
    if vcs_backend.controls_location(location):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/vcs/git.py", line 364, in controls_location
    log_failed_cmd=False)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/vcs/versioncontrol.py", line 632, in run_command
    log_failed_cmd=log_failed_cmd)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 190, in call_subprocess
    stdout=subprocess.PIPE, cwd=cwd, env=env,
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.7/dist-packages/tracer-0.1-py3.7.egg'

P.S. Thank you for responding.

**Comment by rhelmot** [comment]
I have no idea what you've done. My initial guess is it's something wrong with the tracer package, which needs to be provided by https://github.com/angr/tracer and not `pip install tracer`.

**Comment by KittyTechnoProgrammer** [comment]
Ok. So I uninstalled the sortedcontianers and re-ran setup.py install. Now I'm getting the error : 

INFO    | 2019-12-16 19:52:29,324 | rex.Crash | Loading rop gadgets from cache file /opt/rex/tests/../../binaries/tests_data/rop_gadgets_cache/write_what_where_shadow_stack...
Traceback (most recent call last):
  File "test_explore.py", line 48, in <module>
    run_all()
  File "test_explore.py", line 34, in run_all
    all_functions[f]()
  File "test_explore.py", line 21, in test_write_what_where_shadowstack
    crash = rex.Crash(target, inp, rop_cache_path=os.path.join(cache_location, "write_what_where_shadow_stack"))
  File "/usr/local/lib/python3.7/dist-packages/rex-0.2-py3.7.egg/rex/crash.py", line 119, in __init__
  File "/usr/local/lib/python3.7/dist-packages/rex-0.2-py3.7.egg/rex/crash.py", line 565, in _work
  File "/usr/local/lib/python3.7/dist-packages/rex-0.2-py3.7.egg/rex/crash.py", line 612, in _trace
  File "/usr/local/lib/python3.7/dist-packages/archr/arsenal/__init__.py", line 50, in fire
    with self.fire_context(*args, **kwargs) as flight:
  File "/usr/lib/python3.7/contextlib.py", line 239, in helper
    return _GeneratorContextManager(func, args, kwds)
  File "/usr/lib/python3.7/contextlib.py", line 82, in __init__
    self.gen = func(*args, **kwds)
TypeError: fire_context() got an unexpected keyword argument 'channel'

P.S. Thank you for responding so fast

**Comment by KittyTechnoProgrammer** [comment]
I reported this error almost a month ago. The one with the TypeError: fire_context() got an unexpected keyword argument 'channel'. The link to the error is at : https://github.com/shellphish/rex/issues/56

**Comment by rhelmot** [comment]
@zardus promised to fix it tomorrow 12 days ago and then didn't. I think he pawned the TODO off to @ltfish, who has been on vacation. I absolutely refuse to get sucked back into the trash fire that is rex/archr.

**Comment by KittyTechnoProgrammer** [comment]
Sorry. Was doing some research. Why do you call it a "trash fire"?

**Comment by zardus** [comment]
I didn't pawn it off; just haven't had time yet.

**Comment by KittyTechnoProgrammer** [comment]
I didn't think that (believe me I know how long it can take with life in the way for me school). However I was running some other tests, and I just so happened to stumble upon the "SortedKeyList".

**Comment by KittyTechnoProgrammer** [comment]
Is there anything I could do to help with the "channel" bug though.
