### ISSUE TITLE
ImportError: cannot import name 'TracerPoV' from 'tracer' 

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [angr/rex#64]
Was trying to run one of the examples to ensure everything works correctly, and ended up getting this error

Traceback (most recent call last):
  File "test_explore.py", line 6, in <module>
    import rex
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/rex-0.2-py3.8.egg/rex/__init__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/rex-0.2-py3.8.egg/rex/crash.py", line 16, in <module>
ImportError: cannot import name 'TracerPoV' from 'tracer' (/usr/local/lib/python3.8/dist-packages/tracer-0.3.2-py3.8.egg/tracer.py)

P.S. Thank you volunteers for working on the angr projects. Hope this lifts some spirits.

**Comment by twizmwazin** [comment]
You've installed `tracer` from pypi. This is not the tracer package we use. The tracer package used by rex is here: https://github.com/angr/tracer. Install that and you should be good to go!

**Comment by KittyTechnoProgrammer** [comment]
Thank you
