### ISSUE TITLE
Failed to run + issues installing

### ISSUE THREAD

**Issue by huntergregal** [angr/rex#70]
Hey,

I made an virtualenv and ran setup.py - got a few issues related to it failing to install modules from the github links.

After getting those installed i hit an error with the wrong `tracer` being installed.

I removed that tracer and fixed it by installing the correct tracer.

Now I can import rex but get an error when calling `rex.Crash()`

## script snippet
```
crash = rex.Crash('./speedrun-004', crashData)
#crash = rex.Crash('/home/user/ws/fuzz_prac/speedrun-004', crashData) # same error
crash = rex.Crash(tt, crashData)
```

## crash
```
(venv) user:~/ws/fuzz_prac$ python3 rexTest.py 
WARNING | 2021-01-17 21:34:04,131 | cle.loader | <_io.BytesIO object at 0x7f6f21b68360>: base_addr was specified but the object is not PIC. specify force_rebase=True to override
Traceback (most recent call last):
  File "rexTest.py", line 13, in <module>
    crash = rex.Crash(tt, crashData)
  File "/opt/rex/venv/lib/python3.8/site-packages/rex-0.2-py3.8.egg/rex/crash.py", line 105, in __init__
  File "/opt/rex/venv/lib/python3.8/site-packages/rex-0.2-py3.8.egg/rex/crash.py", line 511, in _initialize
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/angr_project.py", line 48, in fire
    _,_,_,self._mem_mapping = self.scout_bow.fire()
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/datascout.py", line 123, in fire
    raise ArchrError("DataScout failed to get argv from the target process.\n"
archr.errors.ArchrError: DataScout failed to get argv from the target process.
stdout: b''
stderr: b''
Exception ignored in: <function Target.__del__ at 0x7f6f23a42c10>
Traceback (most recent call last):
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/targets/__init__.py", line 177, in __del__
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/targets/local_target.py", line 53, in remove
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/targets/__init__.py", line 76, in remove
AttributeError: 'NoneType' object has no attribute 'suppress'
(venv) user:~/ws/fuzz_prac$ python3 rexTest.py 
Traceback (most recent call last):
  File "rexTest.py", line 12, in <module>
    crash = rex.Crash('/home/user/ws/fuzz_prac/speedrun-004', crashData)
  File "/opt/rex/venv/lib/python3.8/site-packages/rex-0.2-py3.8.egg/rex/crash.py", line 78, in __init__
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/qemu_tracer.py", line 43, in __init__
    super().__init__(target, **kwargs)
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/__init__.py", line 20, in __init__
    self.nock()
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/__init__.py", line 28, in nock
    self.target.inject_path(b, os.path.join(self.target.tmpwd, self.REQUIRED_ARROW))
AttributeError: 'str' object has no attribute 'inject_path'
```

import to note that I get a very similiar error if I try to call Crash using an `archr` object instead:

## script snippet
```
tt = archr.targets.LocalTarget(['/home/user/ws/fuzz_prac/speedrun-004'])
crash = rex.Crash(tt, crashData)
```

## crash

```
(venv) user:~/ws/fuzz_prac$ python3 rexTest.py 
WARNING | 2021-01-17 21:40:03,712 | cle.loader | <_io.BytesIO object at 0x7f0712a83360>: base_addr was specified but the object is not PIC. specify force_rebase=True to override
Traceback (most recent call last):
  File "rexTest.py", line 11, in <module>
    crash = rex.Crash(tt, crashData)
  File "/opt/rex/venv/lib/python3.8/site-packages/rex-0.2-py3.8.egg/rex/crash.py", line 105, in __init__
  File "/opt/rex/venv/lib/python3.8/site-packages/rex-0.2-py3.8.egg/rex/crash.py", line 511, in _initialize
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/angr_project.py", line 48, in fire
    _,_,_,self._mem_mapping = self.scout_bow.fire()
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/arsenal/datascout.py", line 123, in fire
    raise ArchrError("DataScout failed to get argv from the target process.\n"
archr.errors.ArchrError: DataScout failed to get argv from the target process.
stdout: b''
stderr: b''
Exception ignored in: <function Target.__del__ at 0x7f071495dc10>
Traceback (most recent call last):
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/targets/__init__.py", line 177, in __del__
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/targets/local_target.py", line 53, in remove
  File "/opt/rex/venv/lib/python3.8/site-packages/archr-8.20.9.2-py3.8.egg/archr/targets/__init__.py", line 76, in remove
AttributeError: 'NoneType' object has no attribute 'suppress'

```

**Comment by Kyle-Kyle** [comment]
can you share the binary and the input?
I can have a look at it.
maybe because of the crazy updates recently.

**Comment by huntergregal** [comment]
Sure thing - the binary is from archive.ooo (speedrun-004), and a crash a generated with AFL.


[sample.tar.gz](https://github.com/angr/rex/files/5831797/sample.tar.gz)

**Comment by huntergregal** [comment]
i think i narrowed this issue down.

It's the same as https://github.com/angr/archr/issues/63 

there's some sort of pathing issue with archr. But moving all of my sample.tar.gz files into the root of the `archr` repo directory and running from there with 

```
tt = archr.targets.LocalTarget(['./speedrun-004'], target_os='linux', target_arch='x86_64')
print('[+] Archr target made')
crash = rex.Crash(tt, crashData)
```
(notice relative path for target name)

this seems to work in that it kicks off processing. I'll let you know how it goes when it completes :)

**Comment by huntergregal** [comment]
if it helps here's a strace of a failed rex attempt - grepping for archr files that could not be found.

if I had to guess it has to do with archr's setup.py and arsenal/arrows not actually being present in the source.

`cat trace.txt |grep "No such" |grep archr|grep -v crash.py > missing.txt`

[missing.txt](https://github.com/angr/rex/files/5832025/missing.txt)

**Comment by rhelmot** [comment]
None of those missing files are actually errors - that's just how python works, it checks a handful of paths to see if they exist when importing a module to prefer them over `__init__.py`. I think this is really just that archr issue.
